
services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passer
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/schoolspring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=passer
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8140:8084"
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passer
      - POSTGRES_DB=schoolspring
    ports:
      - "5434:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
